[package]
name = "antirev"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
argon2 = "0.5.3"
askama = "0.12.1"
diesel = { version = "2.2.2", features = ["postgres", "uuid"] }
dotenvy = "0.15.7"
uuid = { version = "1.10.0", features = ["v4"] }
